---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_CPANEL_USERNAME/public_html
    - /bin/rsync -av --exclude='.git*' --exclude='.cpanel.yml' --exclude='README.md' --exclude='prd.md' * $DEPLOYPATH
